### ISSUE TITLE
Replace com.example.myextension with hash_ssh's proper extension key

### ISSUE THREAD

**Issue by xurizaemon** [DevelopCENTS/civicrm-hash-ssn#3]
There are a few instances of com.example.myextension left in the codebase.

* https://github.com/DevelopCENTS/civicrm-hash-ssn/search?utf8=%E2%9C%93&q=com.example.myextension&type=

Not sure if these will actually cause trouble but you probably want to replace them.

Could also conflict with other extensions using that default string, IDK.

**Comment by dmwhite823** [comment]
This should be resolved now. 
Thanks for pointing this out. I thought my earlier grep's and sed's had taken care of the remaining instances.
